# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &default
 adapter: postgresql
 encoding: unicode
 pool: 5
 database: travelbucketlist_development

test:
 <<: *default
 database: travelbucketlist_test

production:
 <<: *default
 database: travelbucketlist_production
 username: ruby-getting-started
 password: <%= ENV['RUBY-GETTING-STARTED_DATABASE_PASSWORD'] %>
